// src/components/personalData.vue
<template>
  <div>
    <span>Hi, I'm</span>
    <h1>Juan Castañeda</h1>
    <h2><VueWriter :array="arr" :eraseSpeed="50" :typeSpeed="50" /></h2>
    <p>a.k.a <a href="https://twitter.com/PejeDev">PejeDev</a></p>
    <p class="glass-frame">
      I'm a Senior Software Developer based in Bogota, Colombia. <br />
      I'm currently working at
      <a href="https://www.9ncr.com/">9North</a> as a Senior Frontend Developer.
      <br />
      Also at my free time slaying some bugs and adding new features to
      <a href="https://m-35.co/">M-35</a> as Main Video Game Developer.
    </p>
  </div>
</template>

<script lang="js">
import { defineComponent } from "vue";
import VueWriter from "vue-writer";

export default defineComponent({
	name: "PersonalData",
	data() {
    return {
      arr: [
        "Senior Software Developer",
        "Video Game Developer Enthusiast",
        "King Of The Meerkats",

    ]}
  }
});
</script>

<style scoped>
.glass-frame {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border-radius: 10px;
  padding: 10px;
  margin: 10px 0;
  line-height: 24px;
}
</style>

// src/components/home/personal-data/index.tsx
'use client'
import Style from './personal-data.module.css'
import Typewriter from 'typewriter-effect'

export function PersonalData (): JSX.Element {
  return (
    <div>
      <span>Hi, I&apos;m</span>
      <h1>Juan Castañeda</h1>
      <span><Typewriter
        options={{
          strings: ['Senior Software Developer', 'Video Game Developer Enthusiast', 'King Of The Meerkats'],
          autoStart: true,
          loop: true,
          delay: 25,
          deleteSpeed: 25
        }}
      /></span>
      <p>a.k.a <a href="https://twitter.com/PejeDev">PejeDev</a></p>
      <p className={Style.glassFrame}>
        I&apos;m a Senior Software Developer based in Bogota, Colombia. <br />
        I&apos;m currently working at&nbsp;
        <a href="https://www.9ncr.com/">9North</a> as a Senior Frontend Developer.
        <br />
        Also at my free time slaying some bugs and adding new features to&nbsp;
        <a href="https://m-35.co/">M-35</a> as Main Video Game Developer.
      </p>
    </div>
  )
}
